packages:
  - packages/*
  - apps/*
  - website
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@swc/core'
  - appium
  - detox
  - dtrace-provider
  - edgedriver
  - electron
  - esbuild
  - geckodriver
  - nx
  - sharp
  - sqlite3
