name: React Native Harness for Android
description: Run React Native Harness tests on Android
inputs:
  app:
    description: The path to the Android app (.apk)
    required: true
  runner:
    description: The runner to use
    required: true
    type: string
  projectRoot:
    description: The project root directory
    required: false
    type: string
  uploadVisualTestArtifacts:
    description: Whether to upload visual test diff and actual images as artifacts
    required: false
    type: boolean
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Load React Native Harness configuration
      id: load-config
      shell: bash
      env:
        INPUT_RUNNER: ${{ inputs.runner }}
        INPUT_PROJECTROOT: ${{ inputs.projectRoot }}
      run: |
        node ${{ github.action_path }}/../shared/index.cjs
    - name: Verify Android config
      shell: bash
      run: |
        CONFIG='${{ steps.load-config.outputs.config }}'
        if [ -z "$CONFIG.config.device.avd" ] || [ "$CONFIG.config.device.avd" = "null" ]; then
          echo "Error: AVD config is required for Android emulators"
          echo "Please define the 'avd' property in the runner config"
          exit 1
        fi
    - name: Get architecture of the runner
      id: arch
      shell: bash
      run: |
        case "${{ runner.arch }}" in
          X64)
            echo "arch=x86_64" >> $GITHUB_OUTPUT
            ;;
          ARM64)
            echo "arch=arm64-v8a" >> $GITHUB_OUTPUT
            ;;
          ARM32)
            echo "arch=armeabi-v7a" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "arch=x86_64" >> $GITHUB_OUTPUT
            ;;
        esac
    - name: Enable KVM group perms
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        ls /dev/kvm
    - name: Compute AVD cache key
      id: avd-key
      shell: bash
      run: |
        CONFIG='${{ steps.load-config.outputs.config }}'
        AVD_CONFIG=$(echo "$CONFIG" | jq -c '.config.device.avd')
        AVD_CONFIG_HASH=$(echo "$AVD_CONFIG" | sha256sum | cut -d' ' -f1)
        ARCH="${{ steps.arch.outputs.arch }}"
        CACHE_KEY="avd-$ARCH-$AVD_CONFIG_HASH"
        echo "key=$CACHE_KEY" >> $GITHUB_OUTPUT
    - name: Restore AVD cache
      uses: actions/cache/restore@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd
          ~/.android/adb*
        key: ${{ steps.avd-key.outputs.key }}
    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ fromJson(steps.load-config.outputs.config).config.device.avd.apiLevel }}
        arch: ${{ steps.arch.outputs.arch }}
        profile: ${{ fromJson(steps.load-config.outputs.config).config.device.avd.profile }}
        disk-size: ${{ fromJson(steps.load-config.outputs.config).config.device.avd.diskSize }}
        heap-size: ${{ fromJson(steps.load-config.outputs.config).config.device.avd.heapSize }}
        force-avd-creation: false
        avd-name: ${{ fromJson(steps.load-config.outputs.config).config.device.name }}
        disable-animations: true
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: echo "Generated AVD snapshot for caching."
    - name: Save AVD cache
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.android/avd
          ~/.android/adb*
        key: ${{ steps.avd-key.outputs.key }}
    - name: Run E2E tests
      id: run-tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        working-directory: ${{ inputs.projectRoot }}
        api-level: ${{ fromJson(steps.load-config.outputs.config).config.device.avd.apiLevel }}
        arch: ${{ steps.arch.outputs.arch }}
        force-avd-creation: false
        avd-name: ${{ fromJson(steps.load-config.outputs.config).config.device.name }}
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: |
          echo $(pwd)
          adb install -r ${{ inputs.app }}
          pnpm react-native-harness --harnessRunner ${{ inputs.runner }}
    - name: Upload visual test artifacts
      if: always() && inputs.uploadVisualTestArtifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: visual-test-diffs-android
        path: |
          ${{ inputs.projectRoot }}/**/__image_snapshots__/**/*-diff.png
          ${{ inputs.projectRoot }}/**/__image_snapshots__/**/*-actual.png
        if-no-files-found: ignore
